import photo1 from "../assets/images/images1.jpg";
import photo2 from "../assets/images/images.jpg";
import mua from "../assets/images/Untitled2.jpg";
export const navLinks = [
  { href: "/profile", label: "Profile", loggedIn: true },
  { href: "/signup", label: "Register", loggedIn: false },
  { href: "/signin", label: "Login", loggedIn: false },
  { href: "/signout", label: "Logout", loggedIn: true },
];

export const hRate = [30, 30, 30, 30];

export const days = [
  { d: "Pn", av: false, dayShift: false, nightShift: false },
  { d: "Wt", av: false, dayShift: false, nightShift: false },
  { d: "Śr", av: false, dayShift: false, nightShift: false },
  { d: "Cz", av: false, dayShift: false, nightShift: false },
  { d: "Pt", av: false, dayShift: false, nightShift: false },
  { d: "Sb", av: false, dayShift: false, nightShift: false },
  { d: "Nd", av: false, dayShift: false, nightShift: false },
];

export const lngsOptions = [
  "Angielski",
  "Niemiecki",
  "Holenderski",
  "Ukraiński",
  "Rosyjski",
  "Hiszpański",
];
export const levelOptions = ["A1", "A2", "B1", "B2", "C1", "C2"];

export const hourPayArray = ["Dzień", "Noc", "Weekend -dzień", "Weekend-noc"];

export const nationalities = [
  "Wybierz",
  "Afghan",
  "Albanian",
  "Algerian",
  "American",
  "Andorran",
  "Angolan",
  "Antiguans",
  "Argentinean",
  "Armenian",
  "Australian",
  "Austrian",
  "Azerbaijani",
  "Bahamian",
  "Bahraini",
  "Bangladeshi",
  "Barbadian",
  "Barbudans",
  "Batswana",
  "Belarusian",
  "Belgian",
  "Belizean",
  "Beninese",
  "Bhutanese",
  "Bolivian",
  "Bosnian",
  "Brazilian",
  "British",
  "Bruneian",
  "Bulgarian",
  "Burkinabe",
  "Burmese",
  "Burundian",
  "Cambodian",
  "Cameroonian",
  "Canadian",
  "Cape Verdean",
  "Central African",
  "Chadian",
  "Chilean",
  "Chinese",
  "Colombian",
  "Comoran",
  "Congolese",
  "Costa Rican",
  "Croatian",
  "Cuban",
  "Cypriot",
  "Czech",
  "Danish",
  "Djibouti",
  "Dominican",
  "Dutch",
  "East Timorese",
  "Ecuadorean",
  "Egyptian",
  "Emirian",
  "Equatorial Guinean",
  "Eritrean",
  "Estonian",
  "Ethiopian",
  "Fijian",
  "Filipino",
  "Finnish",
  "French",
  "Gabonese",
  "Gambian",
  "Georgian",
  "German",
  "Ghanaian",
  "Greek",
  "Grenadian",
  "Guatemalan",
  "Guinea-Bissauan",
  "Guinean",
  "Guyanese",
  "Haitian",
  "Herzegovinian",
  "Honduran",
  "Hungarian",
  "I-Kiribati",
  "Icelander",
  "Indian",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Irish",
  "Israeli",
  "Italian",
  "Ivorian",
  "Jamaican",
  "Japanese",
  "Jordanian",
  "Kazakhstani",
  "Kenyan",
  "Kittian and Nevisian",
  "Kuwaiti",
  "Kyrgyz",
  "Laotian",
  "Latvian",
  "Lebanese",
  "Liberian",
  "Libyan",
  "Liechtensteiner",
  "Lithuanian",
  "Luxembourger",
  "Macedonian",
  "Malagasy",
  "Malawian",
  "Malaysian",
  "Maldivan",
  "Malian",
  "Maltese",
  "Marshallese",
  "Mauritanian",
  "Mauritian",
  "Mexican",
  "Micronesian",
  "Moldovan",
  "Monacan",
  "Mongolian",
  "Moroccan",
  "Mosotho",
  "Motswana",
  "Mozambican",
  "Namibian",
  "Nauruan",
  "Nepalese",
  "New Zealander",
  "Nicaraguan",
  "Nigerian",
  "Nigerien",
  "North Korean",
  "Northern Irish",
  "Norwegian",
  "Omani",
  "Pakistani",
  "Palauan",
  "Panamanian",
  "Papua New Guinean",
  "Paraguayan",
  "Peruvian",
  "Polish",
  "Portuguese",
  "Qatari",
  "Romanian",
  "Russian",
  "Rwandan",
  "Saint Lucian",
  "Salvadoran",
  "Samoan",
  "San Marinese",
  "Sao Tomean",
  "Saudi",
  "Scottish",
  "Senegalese",
  "Serbian",
  "Seychellois",
  "Sierra Leonean",
  "Singaporean",
  "Slovakian",
  "Slovenian",
  "Solomon Islander",
  "Somali",
  "South African",
  "South Korean",
  "Spanish",
  "Sri Lankan",
  "Sudanese",
  "Surinamer",
  "Swazi",
  "Swedish",
  "Swiss",
  "Syrian",
  "Taiwanese",
  "Tajik",
  "Tanzanian",
  "Thai",
  "Togolese",
  "Tongan",
  "Trinidadian or Tobagonian",
  "Tunisian",
  "Turkish",
  "Tuvaluan",
  "Ugandan",
  "Ukrainian",
  "Uruguayan",
  "Uzbekistani",
  "Venezuelan",
  "Vietnamese",
  "Welsh",
  "Yemenite",
  "Zambian",
  "Zimbabwean",
];

export const workLocations = [
  "Warszawa-Bemowo",
  "Warszawa-Białołęka",
  "Warszawa-Bielany",
  "Warszawa-Mokotów",
  "Warszawa-Ochota",
  "Warszawa-Praga Południe",
  "Warszawa-Praga Północ",
  "Warszawa-Rembertów",
  "Warszawa-Śródmieście",
  "Warszawa-Targówek",
  "Warszawa-Ursus",
  "Warszawa-Ursynów",
  "Warszawa-Wawer",
  "Warszawa-Wesoła",
  "Warszawa-Wilanów",
  "Warszawa-Włochy",
  "Warszawa-Wola",
  "Warszawa-Żoliborz",
  "Stare Babice",
  "Izabelin",
  "Łomianki",
  "Jabłonna",
  "Wieliszew",
  "Legionowo",
  "Nieporęt",
  "Marki",
  "Kobyłka",
  "Wołomin",
  "Ząbki",
  "Zielonka",
  "Sulejówek",
  "Halinów",
  "Wiązowna",
  "Józefów",
  "Otwock",
  "Konstancin Jeziorna",
  "Karczew",
  "Góra Kalwaria",
  "Piaseczno",
  "Lesznowola",
  "Raszyn",
  "Nadarzyn",
  "Grodzisk Mazowiecki",
  "Milanówek",
  "Brwinów",
  "Michałowice",
  "Pruszków",
  "Piastów",
  "Błonie",
  "Ożarów Mazowiecki",
];

export const offers = [
  {
    _id: "1",
    addedBy: {
      _id: "6806b25e3bbff7bcb044fdde",
      name: "Marcin",
      surname: "Widomski",
    },
    category: 1,
    numberOfKids: 3,
    age: [2, 4, 5],
    description: "Dzieci w wieku 4 i 6 lat wymagają opieki",
    urgent: false,
    location: "Piaseczno",
    hourlyRate: 30,
    createdAt: new Date(),
    updatedAt: "",
    reactions: [
      {
        _id: "67f81d34544982f02fd14732",
        name: "Barbara",
        surname: "Nowak",
        photoUrl: photo1,
      },
    ],
    skills: [],
    services: [],
    mobile: "+48 222 333 444",
  },
  {
    _id: "2",
    addedBy: {
      _id: "6806b25e3bbff7bcb044fdde",
      name: "Marcin",
      surname: "Widomski",
    },
    category: 2,
    age: [82],
    description: "Starsza osoba potrzebuje opieki całodobowo",

    urgent: true,
    location: "Warszawa, Ursynów",
    hourlyRate: 35,
    createdAt: new Date(),
    updatedAt: "",
    reactions: [],
    skills: [],
    services: [],
    mobile: "+48 222 333 444",
  },
  {
    _id: "3",
    addedBy: {
      _id: "6806b25e3bbff7bcb044fdde",
      name: "Marcin",
      surname: "Widomski",
    },
    category: 3,
    age: [22],
    level: "znaczny",
    description: "Niepełnosprawna osoba potrzebuje opieki całodobowo",
    urgent: false,
    location: "Warszawa, Bemowo",
    hourlyRate: 40,
    createdAt: new Date(),
    updatedAt: "",
    reactions: [
      {
        _id: "6806b25e3bbff7bcb044f876",
        name: "Jadwiga",
        surname: "Kowalska",
        photoUrl: photo2,
      },
    ],
    skills: [],
    services: [],
    mobile: "+48 222 333 444",
    disabilityLevel: "Lekki",
  },

  {
    _id: "4",
    addedBy: {
      _id: "6806b25e3bbff7bcb044fdde",
      name: "Marcin",
      surname: "Widomski",
    },
    mobile: "+48 222 333 444",
    category: 1,
    numberOfKids: 1,
    age: [2],
    description: "Dziecko w wieku 4 wymaga opieki",
    urgent: true,
    location: "Marki",
    hourlyRate: 45,
    createdAt: new Date(),
    updatedAt: "",
    reactions: [
      {
        _id: "67f81d34544982f02fd14732",
        name: "Barbara",
        surname: "Nowak",
        photoUrl: photo1,
      },
      {
        _id: "6806b25e3bbff7bcb044f876",
        name: "Jadwiga",
        surname: "Kowalska",
        photoUrl: photo2,
      },
    ],
    skills: [],
    services: [],
  },
];

export const demoUser = {
  _id: "6806b25e3bbff7bcb044fdde",
  name: "Marcin",
  surname: "Widomski",
  role: "parent",
  locations: ["Warszawa-Praga Południe"],
  mobile: "+48 222 333 444",
  orders: [1, 2, 3, 4],
  languages: [],
  additionalServices: [],
  additionalSkills: [],
  favUsers: [],
  reviews: [],
  photoUrl: mua,
};
export const demoGuardians = [
  {
    _id: "6806b25e3bbff7bcb044fdde",
    name: "Marcin",
    surname: "Widomski",
    role: "parent",
    locations: ["Warszawa-Praga Południe"],
    mobile: "+48 222 333 444",
    orders: [1, 2, 3, 4],
    languages: [],
    additionalServices: [],
    additionalSkills: [],
    favUsers: [],
    reviews: [],
    photoUrl: mua,
    reviewsStarsAverage: 4,
    hourRate: [30, 30, 30, 30],
  },
  {
    _id: "67f81d34544982f02fd14732",
    name: "Barbara",
    surname: "Nowak",
    role: "nanny",
    workingDays: [
      { d: "Pn", av: false, dayShift: false, nightShift: false },
      { d: "Wt", av: false, dayShift: false, nightShift: false },
      { d: "Śr", av: false, dayShift: false, nightShift: false },
      { d: "Cz", av: true, dayShift: true, nightShift: false },
      { d: "Pt", av: false, dayShift: false, nightShift: false },
      { d: "Sb", av: true, dayShift: false, nightShift: true },
      { d: "Nd", av: false, dayShift: false, nightShift: false },
    ],
    languages: [
      { lng: "Niemiecki", level: "B1" },
      { lng: "Rosyjski", level: "C1" },
    ],
    hourRate: [30, 30, 30, 30],
    age: 35,
    mobile: "+48 123 456 789",
    photoUrl: photo1,
    additionalServices: [],
    additionalSkills: [],
    favUsers: [],
    reviews: [],
    locations: ["Warszawa-Bielany"],
    reviewsStarsAverage: 5,
  },
  {
    _id: "6806b25e3bbff7bcb044f876",
    name: "Jadwiga ",
    surname: "Kowalska",
    role: "nanny",
    workingDays: [
      { d: "Pn", av: true, dayShift: true, nightShift: false },
      { d: "Wt", av: true, dayShift: true, nightShift: false },
      { d: "Śr", av: true, dayShift: true, nightShift: false },
      { d: "Cz", av: true, dayShift: true, nightShift: false },
      { d: "Pt", av: true, dayShift: true, nightShift: false },
      { d: "Sb", av: true, dayShift: false, nightShift: true },
      { d: "Nd", av: false, dayShift: false, nightShift: false },
    ],
    languages: [
      { lng: "Niemiecki", level: "B1" },
      { lng: "Angielski", level: "C1" },
    ],
    hourRate: [35, 35, 35, 40],
    age: 35,
    mobile: "+48 789 567 234",
    photoUrl: photo2,
    additionalServices: [],
    additionalSkills: [],
    favUsers: [],
    reviews: [],
    locations: ["Warszawa-Wawer"],
    reviewsStarsAverage: 4,
  },
];

////////////////////////////////////////////////////

export const order1 = {
  _id: 4,
  senderId: "6806b25e3bbff7bcb044f876",
  category: 1,
  numberOfKids: 3,
  age: [2, 4, 3],
  description: "Dzieci w wieku 2 i  4 lata -potrzebna niania",
  urgent: true,
  location: "Marki",
  hourlyRate: 45,
  contact: "+48666555333",
  skills: [],
  services: [],
  createdAt: "",
  updatedAt: "",
  reactions: ["6806b25e3bbff7bcb044fdde", "6806b25e3bbff7bcb044fre4"],
  active: true,
};
export const order2 = {
  _id: 5,
  senderId: "6806b25e3bbff7bcb044fdde",
  category: 2,
  age: [82],
  description:
    "Starsza osoba potrzebuje opieki całodobowo. Starsza osoba potrzebuje opieki całodobowo.Starsza osoba potrzebuje opieki całodobowo.Starsza osoba potrzebuje opieki całodobowo. Starsza osoba potrzebuje opieki całodobowo. Starsza osoba potrzebuje opieki całodobowo.Starsza osoba potrzebuje opieki całodobowo.Starsza osoba potrzebuje opieki całodobowo.Starsza osoba potrzebuje opieki całodobowo. Starsza osoba potrzebuje opieki całodobowo.Starsza osoba potrzebuje opieki całodobowo.Starsza osoba potrzebuje opieki całodobowo. ",
  urgent: false,
  location: "Warszawa, Bemowo",
  hourlyRate: 40,
  contact: "+48777666555",
  skills: [],
  services: [],
  createdAt: "",
  updatedAt: "",
  reactions: [
    "67f81d34544982f02fd14732",
    "6806b25e3bbff7bcb044fre4",
    "6806b25e3bbff7bcb044f876",
    "6806b25e3bbff7bcb044fre4",
    "6806b25e3bbff7bcb044f876",
    "6806b25e3bbff7bcb044fre4",
  ],
  active: true,
};
export const order3 = {
  _id: 3,
  senderId: "6806b25e3bbff7bcb044fre4",
  category: 3,
  age: [22],
  disabilityLevel: "znaczny",
  description: "Niepełnosprawna osoba potrzebuje opieki całodobowo",
  urgent: false,
  location: "Warszawa, Bemowo",
  hourlyRate: 40,
  contact: "+48333444555",
  skills: [],
  services: [],
  createdAt: "",
  updatedAt: "",
  reactions: ["6806b25e3bbff7bcb044f876"],
  active: true,
};

export const categories = [
  {
    value: 1,
    text: "Opieka nad dzieckiem/dziećmi",
  },
  {
    value: 2,
    text: "Opieka nad osobą starszą",
  },
  {
    value: 3,
    text: "Opieka nad osobą niepełnosprawną",
  },
];

export const disabilityLevels = ["lekki", "umiarkowany", "znaczny"];
